name: Execute Tests
on: 
  workflow_dispatch:
jobs: 
  ExecuteTests:
    name: 'Executing automated Playwright tests'
    runs-on: ubuntu-latest
    container: 
      image: mcr.microsoft.com/playwright:v1.48.0-jammy
    steps:
    - uses: actions/checkout@v4

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: npm ci

    - name: Run Tests
      run: npm run test
    
    - name: Run Reports
      run: npm run report
    
    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with: 
        name: cucumber-report
        path: reports/